#!/bin/sh
#
# to ignore check : --no-verify

against=`git rev-parse --verify HEAD`

# Creation d'un dossier temporaire.
TMPDIR=`mktemp -d`
# On copie le diff dans un fichier patch.
git diff $against > $TMPDIR/current_change.patch
# On copie le HEAD.
git archive $against | tar -x -C $TMPDIR
# on va dans le dossier temporaire pour appliquer le patch.
cd $TMPDIR
git apply current_change.patch
# on compile avec -Werror.
make WERROR=1

rc=$?

rm -rf $TMPDIR

if [ $rc -ne 0 ]; then
		echo "Erreur !"
		exit $rc
fi
